### ISSUE TITLE
Support spaces in label names

### ISSUE THREAD

**Issue by jan-molak** [mrazauskas/docusaurus-remark-plugin-tab-blocks#191]
Hi @mrazauskas and thanks for your work on this plugin! I'd love to use it for the [Serenity/JS website](https://serenity-js.org).

Do you think it would be possible for you to make the plugin support spaces in label names?

For example, below:
```
    ```json title="spec/config.json" tab={"label":"Chrome headless"}
    // some config
    ```
    
    ```json title="spec/config.json" tab={"label":"Chrome non-headless"}
    // some config
    ```
    
    ```json title="spec/config.json" tab={"label":"Firefox"}
    // some config
    ```
```
Results in the following error:

```
ERROR in ./docs/test-runners/cucumber.mdx
Module build failed (from ../../node_modules/@docusaurus/mdx-loader/lib/index.js):
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseMeta (/Users/jan/Projects/serenity-js/serenity-js/node_modules/docusaurus-remark-plugin-tab-blocks/src/plugin.js:21:29)
    at collectTabNodes (/Users/jan/Projects/serenity-js/serenity-js/node_modules/docusaurus-remark-plugin-tab-blocks/src/plugin.js:64:20)
    at /Users/jan/Projects/serenity-js/serenity-js/node_modules/docusaurus-remark-plugin-tab-blocks/src/plugin.js:114:24
    at overload (/Users/jan/Projects/serenity-js/serenity-js/node_modules/unist-util-visit/index.js:27:12)
    at visit (/Users/jan/Projects/serenity-js/serenity-js/node_modules/unist-util-visit-parents/index.js:56:27)
    at visit (/Users/jan/Projects/serenity-js/serenity-js/node_modules/unist-util-visit-parents/index.js:67:75)
    at visitParents (/Users/jan/Projects/serenity-js/serenity-js/node_modules/unist-util-visit-parents/index.js:29:26)
    at visit (/Users/jan/Projects/serenity-js/serenity-js/node_modules/unist-util-visit/index.js:22:3)
    at transformer (/Users/jan/Projects/serenity-js/serenity-js/node_modules/docusaurus-remark-plugin-tab-blocks/src/plugin.js:107:5)
    at wrapped (/Users/jan/Projects/serenity-js/serenity-js/node_modules/trough/wrap.js:25:19)
    at next (/Users/jan/Projects/serenity-js/serenity-js/node_modules/trough/index.js:57:24)
    at done (/Users/jan/Projects/serenity-js/serenity-js/node_modules/trough/wrap.js:55:16)
    at then (/Users/jan/Projects/serenity-js/serenity-js/node_modules/trough/wrap.js:62:5)
    at wrapped (/Users/jan/Projects/serenity-js/serenity-js/node_modules/trough/wrap.js:45:9)
    at next (/Users/jan/Projects/serenity-js/serenity-js/node_modules/trough/index.js:57:24)
    at done (/Users/jan/Projects/serenity-js/serenity-js/node_modules/trough/wrap.js:55:16)
    at then (/Users/jan/Projects/serenity-js/serenity-js/node_modules/trough/wrap.js:62:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I think the issue is caused by the implicit assumption made in `parseMeta` that label names have no spaces:
https://github.com/mrazauskas/docusaurus-remark-plugin-tab-blocks/blob/8b5ed1aca11a99ab123d9265fd06379cc1ea7847/src/plugin.js#L46


Thanks!

**Comment by mrazauskas** [comment]
Thanks! Glad you find the plugin useful.

This is obviously a bug. I will fix it.

Do you need this for Docusaurus 2? I was about to publish stable version for Docusaurus 3 in a week or two. For instance, it is already used in production on Jest website (see https://github.com/jestjs/jest/pull/14463).

**Comment by jan-molak** [comment]
A patch for Docusaurus 2 would be brilliant, thank you!

**Comment by mrazauskas** [comment]
Fix it on `main`. It targets Docusaurus 3 already. Now I have to figure out how to back port that to v1. Never did something like this before ;D

**Comment by jan-molak** [comment]
Thanks! And good luck! 😄
